
---
clone:
  git:
    image: plugins/git
    depath: 3
    tags: true

kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: bootstrap
  image: node:12.13.0
  commands:
  - npm install
  - npm run ng test

  
# ---
# kind: pipeline
# name: build

# steps:
# - name: bootstrap
#   image: node:12.13.0
#   commands:
#   - npm install

# - name: build
#   image: node:12.13.0
#   commands:
#   - npm build -prod


