---
kind: pipeline
name: develop-pipe

platform:
  os: linux
  arch: amd64

steps:
- name: bootstrap
  image: node:12.13.0
  commands:
  - npm install

- name: test
  image: node:12.13.0
  commands:
  - ng test
  depends_on:
  - bootstrap
  
 - name: e2e
  image: node:12.13.0
  commands:
  - ng e2e
  depends_on:
  - bootstrap
  - test
