---
kind: pipeline
name: develop-pipe

platform:
  os: linux
  arch: amd64

steps:
- name: bootstrap
  image: node:12.13.0
  commands:
  - npm install
  - npm install @angular/cli
  - npm run ng test
  - npm run ng e2e --headless

