version: '2'

services:
  drone-server:
    image: drone/drone:1
    ports:
      - 8765:80
    volumes:
      - ./:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST=7888f7be78d8.ngrok.io
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=abcd1234

      # GitHub Config
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=0d268b8c3f6563737dc1
      - DRONE_GITHUB_CLIENT_SECRET=ab8624a8c2804acd880eeb6f5681975254186760

      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  # runner for docker version
  drone-runner:
    image: drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      ## ^
      ## |如果與server架在不同台設定drone server host name
      ## |如果與server架在同一台直接寫入上面的drone-server

      - DRONE_RPC_PROTO=http ## http or https
      - DRONE_RPC_SECRET=abcd1234 ## 與server設定為一樣的
      - DRONE_RUNNER_CAPACITY=3 ### 設定同時可以跑幾個job
