version: '2'

services:
  drone-server:
    image: drone/drone:1
    ports:
      - 8088:80
    volumes:
      - ./:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST=3633cda5c970.ngrok.io
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=ab8624a8c2804acd880eeb6f5681975254186761

      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=035119fe942b1456b116
      - DRONE_GITHUB_CLIENT_SECRET=2583032b83f42b9eaabfa20597186322aa95e16d

      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

  # runner for docker version
  drone-runner:
    image: drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=ab8624a8c2804acd880eeb6f5681975254186761
      - DRONE_RUNNER_CAPACITY=3
